version: '3.4'

services:
  submissionapi:
    image: otherwisejunk/cci-submissionapi
    ports:
      - '85:80'
    volumes:
      - submissions:/app/LoneAnt/Submissions
      - backups:/app/LoneAnt/Backups
  submissionapi2:
    image: otherwisejunk/cci-submissionapi
    ports:
      - '84:80'
    volumes:
      - submissions:/app/LoneAnt/Submissions
      - backups:/app/LoneAnt/Backups

volumes:
  submissions:
  backups: